### ISSUE TITLE
my's todo list (blender)

### ISSUE THREAD

**Issue by LITl-l** [void2610/PaOn#1]
頑張りましょう。
--------------------------------------------------------------------------------------------------------------------------------------------

- [x] 石(数種類)

- [x] 木(数種類)

- [x] 草(数種類)

- [x] 花(数種類)

- [x] 葉っぱ(数種類) <-- 葉っぱだけでいろんな絵(?)を描けるように細長かったり色々絵作品に使いやすそうな形をお願い

- [x] 木の枝(数種類) <-- 色々絵作品に使いやすそうな形をお願い

- [x] ボルダリングのつかむところ(数種類)

- [x] ベンチ

- [x] 街灯

- [x] 切り株

- [x] シャベル

- [x] 虫取り網

- [x] バケツ

- [x] クレヨン(数種類)

- [x] 自然あそびのキャンバス(要相談) 

- [x] プレイヤー(要相談)

- [x] ボルダリングの柵

- [x] 滑り台

以下後回し
--------------------------------------------------------------------------------------------------------------------------------------------

for @s55536my

**Comment by void2610** [comment]
### **_nice_**
