### ISSUE TITLE
Barracudaで骨格検知

### ISSUE THREAD

**Issue by void2610** [void2610/PaOn#3]

**Comment by LITl-l** [comment]
ref: 
https://github.com/creativeIKEP/HolisticBarracuda
https://github.com/keijiro/HandPoseBarracuda
https://github.com/keijiro/HandLandmarkBarracuda
https://github.com/keijiro/HandPoseBarracuda

**Comment by LITl-l** [comment]
全てApache License 2.0のため、最終的に明記する
